### ISSUE TITLE
can't install it on RN0.72 or RN0.74

### ISSUE THREAD

**Issue by indapublic** [sahha-ai/sahha-react-native#8]
```
Couldn't install Pods. Updating the Pods project and trying again...
Command `pod install` failed.
└─ Cause: CocoaPods could not find compatible versions for pod "sahha-react-native":
  In Podfile:
    sahha-react-native (from `../node_modules/sahha-react-native`)

Specs satisfying the `sahha-react-native (from `../node_modules/sahha-react-native`)` dependency were found, but they required a higher minimum deployment target.
```

Tried to bump deployment target but no luck. 

Cannot find anything in your documentation or probably was bad to find.

Could you point me to this requirement please? Thank you.

**Comment by smileypop** [comment]
The project inside the /example folder uses "react-native": "^0.72.0".

Can you try to build this project and install cocoapods there?

Please let us know if it works.
